# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: 
    - cron: '40 23 * * *' # Run every evening, twenty mins before midnight
  workflow_dispatch:
  push: 
    branches:
      - main
jobs:
  # Main Metrics - Short
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/summary.svg
          committer_message: "📊 updates metrics - summary"
          user: n3rd3x3
          template: classic
          base: activity, community, repositories
          config_timezone: America/Chicago
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_traffic: yes
          plugin_lines: yes
          plugin_discussions: yes
          plugin_discussions_categories: no

 # Recent Activity
  activity-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/activity.svg
          committer_message: "📊 Updates metrics - activity"
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public